version: '2'
services:
  redis:
    image: redis:5-alpine

  db:
    image: mariadb:10
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rails
      MYSQL_DATABASE: speaker_illus
      MYSQL_USER: speaker
      MYSQL_PASSWORD: illustrations
    ports:
      - 3306:3306

  web:
    build: .
    volumes:
      - .:/app
    command: bundle exec rails s
    environment:
      SECRET_KEY_BASE: xptod
      RAILS_DB: speaker_illus
      RAILS_DB_USER: speaker
      RAILS_DB_PASS: illustrations
      RAILS_REDIS: redis
      RAILS_REDIS_CHAN: SpeakerIllustrations_prod
      RAILS_DB_HOST: db
      RAILS_ENV: development
    ports:
      - 8080:3000