development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://<%= ENV.fetch("RAILS_REDIS", "redis") %>:6379/1
  channel_prefix: <%= ENV.fetch("RAILS_REDIS_CHAN", "SpeakerIll_prod") %>
